version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - /home/bakary/devops/docker/3_docker_tomcat/volumes/mysql:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: bakdb1
       MYSQL_USER: user_bak
       MYSQL_PASSWORD: password
     ports:
       - 3306:3306
phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
web:
    depends_on:
      - db
    image: tomcat
    volumes:
      - /home/bakary/devops/docker/3_docker_tomcat/volumes/tomcat/LoginWebApp-1.war:/usr/local/tomcat/webapps/LoginWebApp-1.war
    ports:
      - '8082:8080'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bakdb1
      MYSQL_USER: user_bak
      MYSQL_PASSWORD: password